FROM fedora:43
RUN dnf install -y \
    curl gcc gcc-c++ git glib2-devel libatomic make ninja-build pkgconf-pkg-config python3 \
    && dnf clean all
RUN ln -sf /usr/bin/python3 /usr/bin/python
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup target add x86_64-unknown-linux-musl aarch64-unknown-linux-musl
